name: Workflow by API Call
on:
  repository_dispatch:
    types: [incident_report]  # Custom event type name

jobs:
  handle-incident:
    runs-on: ubuntu-latest
    steps:
      - name: Print incident details
        run: echo "Incident reported"

