name: Manual Trigger 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs: 
  message:    
    runs-on: ubuntu-latest
    steps: 
      - name: echo message
        run: |
          echo "deploying to ${{ inputs.environment }}"

