      - "src/**"
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the main branch
        uses: actions/checkout@v4.2.2

      - name: Run Tests
        run: npm test


