name: webhook trigger

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the main branch
        uses: actions/checkout@v4.2.2
        run: cd src

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test


