name: schedule workflow

on:
  schedule: 
    - cron: "*/5 * * * *"

jobs:
  file_create:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to the main repo
        uses: actions/checkout@v4.2.2

      - name: crate new file in src Directory
        run: touch ./src/test.txt
