name: sheduled trigger workflow
on: 
  schedule:
    - cron: "* * * * *"

jobs: 
  schedule-job:
    runs-on: ubuntu-latest
    steps: 
      - name: echo message
        run: |
          echo "Hello Muhamed"
          echo "Hello Talal"



